# Generated by Django 4.2.10 on 2024-02-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='order',
            new_name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='order_number',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
