# Generated by Django 4.2.10 on 2024-02-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_order_ticket_user_ticket_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='customer',
        ),
    ]
