# Generated by Django 4.2.10 on 2024-02-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_user_ticket_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='customer',
            new_name='order_id',
        ),
    ]
