# Generated by Django 4.2.10 on 2024-05-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_rename_order_id_ticket_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='event_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='payment_status',
            field=models.CharField(max_length=50),
        ),
    ]
