# Generated by Django 4.2.10 on 2024-02-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='media/product_images/')),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vip_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tickets', models.IntegerField()),
                ('available_tickets', models.IntegerField()),
            ],
        ),
    ]
