# Generated by Django 4.2.10 on 2024-02-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0003_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='regular_stripe_id',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='vip_stripe_id',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
